services:
  - type: web
    name: tak-tudy
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: JWT_SECRET
        generateValue: true
      - key: DATA_DIR
        value: ./data
